spring:
  datasource:
    drive-class-name: org.mysql.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:
  configuration:
    map-underscore-to-camel-case: true
  logging:
    file:
      name=logs/application: