spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          stat: debug
          type: trace
  jackson:
    serialization:
      fail-on-empty-beans: false
#  datasource:
#    drive-class-name: org.mysql.Driver
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password:
#  configuration:
#    map-underscore-to-camel-case: true
#    file:
#      name=logs/application: